@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Jan 24 22:16:03 +0330 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto b84f4f6d687e4f41bc78eb9c1cc7dbfd --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot AD4030_FSM_tb_behav xil_defaultlib.AD4030_FSM_tb -log elaborate.log"
call xelab  -wto b84f4f6d687e4f41bc78eb9c1cc7dbfd --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot AD4030_FSM_tb_behav xil_defaultlib.AD4030_FSM_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
